---
jobs:
  - name: unit-tests
    serial: true
    build_logs_to_retain: 250
    plan:
      - { get: bosh-cpi-ruby-gem, trigger: true }
      - task: test
        params:
          RUBY_VERSION: 2.4.4
        file: bosh-cpi-ruby-gem/ci/tasks/test-unit.yml

  - name: publish-minor
    serial: true
    plan:
      - get: bosh-cpi-ruby-gem
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: minor }
      - &publish
        do:
        - put: bosh-cpi-ruby-gem
          params:
            repository: bosh-cpi-ruby-gem/
            tag: version-semver/version
            tag_prefix: v
            only_tag: true
        - task: publish
          file: bosh-cpi-ruby-gem/ci/tasks/publish-gem.yml
          params:
            RUBYGEMS_API_KEY: ((rubygems_api_key))
            RUBY_VERSION: 2.4.4
        - put: version-semver
          params: { file: version-semver/number }

  - name: publish-major
    serial: true
    plan:
      - get: bosh-cpi-ruby-gem
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: major }
      - *publish

  - name: publish-patch
    serial: true
    plan:
      - get: bosh-cpi-ruby-gem
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: patch }
      - *publish

resources:
  - name: bosh-cpi-ruby-gem
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-cpi-ruby.git
      branch: master
      private_key: ((github_deploy_key_bosh-cpi-ruby.private_key))

  - name: version-semver
    type: semver
    source:
      key: current-version
      access_key_id: ((bosh-cpi-ruby_assume_aws_access_key.username))
      secret_access_key: ((bosh-cpi-ruby_assume_aws_access_key.password))
      assume_role_arn: ((bosh-cpi-ruby_assume_aws_access_key.role_arn))
      bucket: bosh-cpi-ruby

resource_types:
- name: semver
  type: docker-image
  source:
    repository: concourse/semver-resource
    tag: 1.6