---
jobs:
  - name: unit-tests
    serial: true
    plan:
      - get: bosh-cpi-ruby-gem
        trigger: true
      - get: bosh-integration-registry-image
      - task: test
        file: bosh-cpi-ruby-gem/ci/tasks/test-unit.yml
        image: bosh-integration-registry-image

  - name: publish-minor
    serial: true
    plan:
      - get: bosh-cpi-ruby-gem
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: minor }
      - &publish
        do:
        - get: bosh-integration-registry-image
        - put: bosh-cpi-ruby-gem
          params:
            repository: bosh-cpi-ruby-gem/
            tag: version-semver/version
            tag_prefix: v
            only_tag: true
        - task: publish
          file: bosh-cpi-ruby-gem/ci/tasks/publish-gem.yml
          image: bosh-integration-registry-image
          params:
            RUBYGEMS_API_KEY: ((rubygems_api_key))
        - put: version-semver
          params: { file: version-semver/number }

  - name: publish-major
    serial: true
    plan:
      - get: bosh-cpi-ruby-gem
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: major }
      - *publish

  - name: publish-patch
    serial: true
    plan:
      - get: bosh-cpi-ruby-gem
        passed: [unit-tests]
        trigger: false
      - get: version-semver
        params: { bump: patch }
      - *publish

resources:
  - name: bosh-cpi-ruby-gem
    type: git
    source:
      uri: git@github.com:cloudfoundry/bosh-cpi-ruby.git
      branch: master
      private_key: ((github_deploy_key_bosh-cpi-ruby.private_key))

  - name: version-semver
    type: semver
    source:
      driver: git
      uri: git@github.com:cloudfoundry/bosh-cpi-ruby.git
      branch: semver
      file: version
      private_key: ((github_deploy_key_bosh-cpi-ruby.private_key))

  - name: bosh-integration-registry-image
    type: registry-image
    source:
      repository: bosh/integration
      username: ((dockerhub_username))
      password: ((dockerhub_password))

resource_types:
- name: semver
  type: docker-image
  source:
    repository: concourse/semver-resource
    tag: 1.6
